name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download Gradle 8.2
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.2-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.2/bin" >> $GITHUB_PATH

      - name: Unzip project
        run: |
          unzip -q ehealth_app_offline_fixed.zip -d .

      - name: Configure gradle properties
        run: |
          echo "android.useAndroidX=true" >> ehealth_app/gradle.properties
          echo "android.enableJetifier=true" >> ehealth_app/gradle.properties

      - name: Generate Gradle wrapper in project
        working-directory: ehealth_app
        run: |
          gradle wrapper --gradle-version 8.2
          chmod +x ./gradlew

      - name: Build debug APK
        working-directory: ehealth_app
        run: |
          ./gradlew :app:assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ehealth_app/app/build/outputs/apk/debug/app-debug.apk
